version: "3"
services:
  backend:
    container_name: backend
    build:
      context: ./backend/app2/
      dockerfile: Dockerfile
    command: >
      sh -c "python app/manage.py wait_for_db &&
             python app/manage.py migrate &&
             python app/manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=app
      - DB_USER=postgres
      - DB_PASS=supersecretpassword
    ports:
      - "8000:8000"
    volumes:
      - ./backend/:/home/backend/
    depends_on:
      - db
    restart: always

  frontend:
    container_name: frontend
    build:
      context: frontend
      dockerfile: Dockerfile
    volumes:
      - './frontend:/usr/src/app'
      - '/usr/src/app/node_modules'
    ports:
      - '5000:5000'
    depends_on:
      - "backend"
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - HOST_URL=http://localhost/:3000

  db:
    container_name: database
    image: postgres
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
      - POSTGRES_DB=app
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=supersecretpassword
    expose:
      - 5432