# Generated by Django 2.1.8 on 2019-06-12 21:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0005_recipe_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('asin', models.CharField(max_length=255)),
                ('score', models.CharField(max_length=255)),
                ('sponsored', models.BooleanField(default=False)),
                ('amazon_choice', models.BooleanField(default=False)),
                ('amazon_prime', models.BooleanField(default=False)),
                ('price', models.DecimalField(max_digits=5, decimal_places=2)),
                ('before_price', models.DecimalField(max_digits=5, decimal_places=2)),
                ('current_price', models.DecimalField(max_digits=5, decimal_places=2)),
                ('currency', models.CharField(max_length=255, blank=True)),
                ('rating', models.CharField(max_length=255, blank=True)),
                ('total_reviews', models.CharField(max_length=255, blank=True)),
                ('discounted', models.BooleanField(default=False)),
                ('url', models.CharField(max_length=255, blank=True)),
                ('thumbnail', models.CharField(max_length=255, blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
